GET http://localhost:3080/users

###
GET http://localhost:3080/users/62991f1cd8cd58d394b999d0

###

POST http://localhost:3080/users
Content-Type: application/json

{
    "name": "Master Nyoman",
    "email": "Nyoman@gmail.com",
    "gender": "male"
}

###

PATCH http://localhost:3080/users/62991f1cd8cd58d394b999d0
Content-Type: application/json

{
    "name": "Master Klo",
    "email": "klo@gmail.com",
    "gender": "non-binary"
}

###
DELETE  http://localhost:3080/users/62991f1cd8cd58d394b999d0
